# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd13451b8a526edf9a7d766cc4930d05883e8194637eaacd244dc07b0a4661a0a32cf85d2e42df145ef87b371b9eadc31438a0b8d1bd5becde8c13de3335baf6

test:
  secret_key_base: 974dabd036f2498e4f04792835d3b9069e87a9b75eb7412c1d17da795726de1e8fdeeaf61fa786158a3d2409d7819483b19779d99fd23d9311168ef4d58a3d71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
